[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "uibench"
version = "0.1.0"
description = "UI Benchmarking Tool"
requires-python = ">=3.11"
authors = [
    {name = "UIBench Team"}
] 